// Exception Handling;

void main() {
  // >>>>>>try on
  // try {
  //   var result = 4 ~/ 0;
  //   print(result);
  // } on IntegerDivisionByZeroException {
  //   print("Can't divide by Zero");
  // }

// try catch
  // try {
  //   var result = 4 ~/ 0;
  //   print(result);
  // } catch (e) {
  //   print(e);
  // }
}
